name: compressor
version: 0.1
summary: Brotli Compressor/Decompressor
description: |
  Compressor is a tool for compressing and decompressing files 
  using Google's Brotli compression technique.

grade: devel
confinement: devmode

apps:
  compressor:
    command: compressor

parts:
  compressor:
    plugin: python
    python-version: python3
    requirements: ./requirements.txt
    source: .
