name: gphotos_cli
description: An unofficial command line tool to upload photos to Google Photos library.
version: 0.0.1
homepage: https://mukilane.github.io
author: mukilane <mukilane@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  googleapis_auth:
  http:
  ini:
  args:
  glob: